# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'City ATMs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for City ATMs

pod 'Alamofire', '~> 4.8.2'
pod 'AlamofireObjectMapper'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'RealmSwift'

end
